name: k6 Test
#  thanks to lukas8219 - https://github.com/lukas8219/rinha-de-backend-2025/blob/main/.github/workflows/test.yaml

on:
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Download Environment
        run: |  
          curl -l https://raw.githubusercontent.com/zanfranceschi/rinha-de-backend-2025/refs/heads/main/payment-processor/docker-compose.yml -o docker-compose-payment-processor.yml
          curl -l https://raw.githubusercontent.com/zanfranceschi/rinha-de-backend-2025/refs/heads/main/rinha-test/rinha.js -o rinha.js
          curl -l https://raw.githubusercontent.com/zanfranceschi/rinha-de-backend-2025/refs/heads/main/rinha-test/requests.js -o requests.js
          curl -l https://raw.githubusercontent.com/zanfranceschi/rinha-de-backend-2025/refs/heads/main/payment-processor/init.sql -o init.sql

      - name: Build and start services
        run: docker-compose -f docker-compose-payment-processor.yml up -d

      - name: Wait for services to be healthy
        run: sleep 5

      - name: Build and start services
        run: cd src && docker-compose up -d --build

      - name: Wait for services to be healthy
        run: |
          # Wait for nginx to be up (adjust port if needed)
          for i in {1..60}; do
            if curl -s http://localhost:9999/ > /dev/null; then
              echo "nginx is up!"
              break
            fi
            echo "Waiting for nginx..."
            sleep 2
          done

      - uses: grafana/setup-k6-action@v1

      - name: Run k6 test
        run: k6 -q -e MAX_REQUESTS=550 run rinha.js
      - name: Create Comment MD File
        run: |
          echo "## k6 Test Results" > comment.md
          echo "Hash: ${{ github.sha }}" >> comment.md
          echo "\`\`\`json" >> comment.md
          cat partial-results.json >> comment.md
          echo "\n\`\`\`" >> comment.md

      - name: Append Docker Compose Logs
        run: |
          echo "## Docker Compose Logs" >> comment.md
          echo '```log' >> comment.md
          cd src && docker-compose logs >> ../comment.md || true
          echo '```' >> comment.md

      - name: Echo comment.md contents
        run: cat comment.md

      - name: Upload comment.md as artifact
        uses: actions/upload-artifact@v4
        with:
            name: comment-md
            path: comment.md
            retention-days: 1
